import { AuthProvider } from "@/components/context/AuthContext";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body className="flex flex-col h-full overflow-x-hidden">
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	);
}
