import type { Metadata } from "next";

import { AuthProvider } from "@/components/context/AuthContext";

import { auth } from "./auth";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html lang="en" className="h-full">
			<body className="flex flex-col h-full overflow-x-hidden">
				<AuthProvider session={session!}>{children}</AuthProvider>
			</body>
		</html>
	);
}
